-- GeoPlans Database Schema and Dummy Data
-- Generated by Antigravity Auditor

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- -------------------------------------------------
-- Table: categories
-- -------------------------------------------------
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `categories` (`id`, `name`) VALUES
(1, 'Música'),
(2, 'Teatro'),
(3, 'Cine'),
(4, 'Gastronomía'),
(5, 'Aire Libre');

-- -------------------------------------------------
-- Table: plans
-- -------------------------------------------------
DROP TABLE IF EXISTS `plans`;
CREATE TABLE `plans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price` decimal(10,2) DEFAULT '0.00',
  `date` datetime NOT NULL,
  `url_source` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_plan_category` (`category_id`),
  CONSTRAINT `fk_plan_category` FOREIGN_KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `plans` (`id`, `title`, `description`, `location`, `price`, `date`, `url_source`, `category_id`) VALUES
(1, 'Concierto de Jazz en el Parque', 'Disfruta de una tarde de jazz suave al aire libre.', 'Parque Central, Valencia', 0.00, '2026-06-15 18:00:00', 'https://agenda.valencia.es/jazz', 1),
(2, 'Festival de Teatro Clásico', 'Obras de Lope de Vega y Calderón.', 'Teatro Principal', 25.50, '2026-07-20 20:30:00', 'https://teatro.es/festival', 2),
(3, 'Ruta de Tapas por el Carmen', 'Recorrido gastronómico por los mejores bares.', 'Barrio del Carmen', 15.00, '2026-05-10 12:00:00', 'https://gastronomy.com/tapas', 4);

SET FOREIGN_KEY_CHECKS = 1;
